pipeline:
  name: test2dds
  identifier: test2dds
  tags: {}
  projectIdentifier: test_kushal
  orgIdentifier: default
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 11m
        tags: {}
