pipeline:
  name: git_scm_queue
  identifier: git_scm_queue
  tags: {}
  projectIdentifier: dfd
  orgIdentifier: default2
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
        tags: {}
