pipeline:
  name: ss
  identifier: ss
  tags: {}
  projectIdentifier: dfd
  orgIdentifier: default2
  stages:
    - stage:
        name: dsd
        identifier: dsd
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
        tags: {}
